import Head from "next/head";
import Image from "next/image";

import SignIn from "@/session/screens/sign-in";

export default function Home() {
  return (
    <>
      <Head>
        <title>Iniciar Sesión</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="h-screen w-screen">
        <section className="gradient-form h-full bg-neutral-200">
          <div className=" h-screen text-neutral-800">
            <div className="block h-full bg-white shadow-lg">
              <div className="g-0 h-full lg:flex lg:flex-wrap">
                <div className="px-4 md:px-0 lg:w-6/12">
                  <div className="md:mx-6 md:p-12">
                    <div className="flex flex-col items-center justify-center text-center">
                      <Image
                        alt="logo"
                        height={200}
                        src="https://tecdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                        width={200}
                      />
                      <h4 className="mb-12 mt-1 pb-1 text-xl font-semibold">CleanCode Team</h4>
                    </div>

                    <p className="mb-4">Ingresa a tu cuenta</p>
                    <SignIn />
                  </div>
                </div>

                <div
                  className="flex items-center rounded-b-lg lg:w-6/12 lg:rounded-r-lg lg:rounded-bl-none"
                  style={{
                    background: "linear-gradient(to right, #3A1078, #2F58CD)",
                  }}
                >
                  <div className="px-4 py-6 text-white md:mx-6 md:p-12">
                    <h4 className="mb-6 text-xl font-semibold">
                      Siempre estamos mejorando para ti 🚀
                    </h4>
                    <p className="text-sm">
                      Es la hora de que te unas a la comunidad de CleanCode Team, donde podrás
                      encontrar los mejores cursos de programación, diseño y marketing digital.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
